<?php // this is an autogenerated file - do not edit (created Wed, 01 Dec 2010 04:07:21 +0100)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'eecmoduleoverviewdefintion' => '/definition.php',
            'arbitmodulephpdocadminclitool' => '/classes/cli_tool.php',
            'eecmoduleoverviewxhtmlhandler' => '/classes/view/handler/xhtml.php',
            'eecoverviewviewmodel' => '/classes/view/model/index.php',
            'eecmoduleoverviewcollectcommand' => '/classes/commands/collect.php',
            'eecoverviewcollectelementstruct' => '/classes/signals/collect_element.php',
            'eecoverviewcollectstruct' => '/classes/signals/collect.php',
            'eecmoduleoverviewcontroller' => '/classes/controller.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
