<?php // this is an autogenerated file - do not edit (created Sat, 27 Nov 2010 01:59:31 +0100)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'eechttpenvironmentdic' => '/dependency_injection_container/http.php',
            'eecenvironmentdic' => '/dependency_injection_container/base.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
